// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: internal/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMetricValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricType    string                 `protobuf:"bytes,1,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricValue   string                 `protobuf:"bytes,3,opt,name=metric_value,json=metricValue,proto3" json:"metric_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricValueRequest) Reset() {
	*x = UpdateMetricValueRequest{}
	mi := &file_internal_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricValueRequest) ProtoMessage() {}

func (x *UpdateMetricValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricValueRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMetricValueRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *UpdateMetricValueRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *UpdateMetricValueRequest) GetMetricValue() string {
	if x != nil {
		return x.MetricValue
	}
	return ""
}

type UpdateMetricValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricValueResponse) Reset() {
	*x = UpdateMetricValueResponse{}
	mi := &file_internal_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricValueResponse) ProtoMessage() {}

func (x *UpdateMetricValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricValueResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricValueResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EncryptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	mi := &file_internal_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptedMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_proto_metrics_proto protoreflect.FileDescriptor

const file_internal_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/metrics.proto\x12\x17metric.alerting.service\"\x7f\n" +
	"\x18UpdateMetricValueRequest\x12\x1f\n" +
	"\vmetric_type\x18\x01 \x01(\tR\n" +
	"metricType\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12!\n" +
	"\fmetric_value\x18\x03 \x01(\tR\vmetricValue\"1\n" +
	"\x19UpdateMetricValueResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"&\n" +
	"\x10EncryptedMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x88\x02\n" +
	"\rMetricService\x12z\n" +
	"\x11UpdateMetricValue\x121.metric.alerting.service.UpdateMetricValueRequest\x1a2.metric.alerting.service.UpdateMetricValueResponse\x12{\n" +
	"\x1aUpdateMetricValueEncrypted\x12).metric.alerting.service.EncryptedMessage\x1a2.metric.alerting.service.UpdateMetricValueResponseBEZCgithub.com/dmitrijs2005/metric-alerting-service/internal/grpc/protob\x06proto3"

var (
	file_internal_proto_metrics_proto_rawDescOnce sync.Once
	file_internal_proto_metrics_proto_rawDescData []byte
)

func file_internal_proto_metrics_proto_rawDescGZIP() []byte {
	file_internal_proto_metrics_proto_rawDescOnce.Do(func() {
		file_internal_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_proto_rawDesc), len(file_internal_proto_metrics_proto_rawDesc)))
	})
	return file_internal_proto_metrics_proto_rawDescData
}

var file_internal_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_metrics_proto_goTypes = []any{
	(*UpdateMetricValueRequest)(nil),  // 0: metric.alerting.service.UpdateMetricValueRequest
	(*UpdateMetricValueResponse)(nil), // 1: metric.alerting.service.UpdateMetricValueResponse
	(*EncryptedMessage)(nil),          // 2: metric.alerting.service.EncryptedMessage
}
var file_internal_proto_metrics_proto_depIdxs = []int32{
	0, // 0: metric.alerting.service.MetricService.UpdateMetricValue:input_type -> metric.alerting.service.UpdateMetricValueRequest
	2, // 1: metric.alerting.service.MetricService.UpdateMetricValueEncrypted:input_type -> metric.alerting.service.EncryptedMessage
	1, // 2: metric.alerting.service.MetricService.UpdateMetricValue:output_type -> metric.alerting.service.UpdateMetricValueResponse
	1, // 3: metric.alerting.service.MetricService.UpdateMetricValueEncrypted:output_type -> metric.alerting.service.UpdateMetricValueResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_metrics_proto_init() }
func file_internal_proto_metrics_proto_init() {
	if File_internal_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_proto_rawDesc), len(file_internal_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_metrics_proto_goTypes,
		DependencyIndexes: file_internal_proto_metrics_proto_depIdxs,
		MessageInfos:      file_internal_proto_metrics_proto_msgTypes,
	}.Build()
	File_internal_proto_metrics_proto = out.File
	file_internal_proto_metrics_proto_goTypes = nil
	file_internal_proto_metrics_proto_depIdxs = nil
}
